// flow-typed signature: 5340cd09f8dfd49087fc3dcdf63ee6e4
// flow-typed version: <<STUB>>/babel-plugin-transform-property-literals_v^6.8.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-property-literals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-property-literals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-property-literals/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-property-literals/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-property-literals/lib/index'>;
}
