// flow-typed signature: 070662d596ec347741f49b71586f21a9
// flow-typed version: <<STUB>>/babel-plugin-minify-simplify_v^0.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-minify-simplify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-minify-simplify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-minify-simplify/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-minify-simplify/lib/pattern-match' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-minify-simplify/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-minify-simplify/lib/index'>;
}
declare module 'babel-plugin-minify-simplify/lib/pattern-match.js' {
  declare module.exports: $Exports<'babel-plugin-minify-simplify/lib/pattern-match'>;
}
