// flow-typed signature: b060411fe5d9e70cbc152bd9562c8cf5
// flow-typed version: <<STUB>>/babel-plugin-transform-node-env-inline_v^0.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-node-env-inline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-node-env-inline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-node-env-inline/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-node-env-inline/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-node-env-inline/lib/index'>;
}
