// flow-typed signature: dc89c71b18ba41b7a184295b8b5a8e50
// flow-typed version: <<STUB>>/babel-plugin-transform-simplify-comparison-operators_v^6.8.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-simplify-comparison-operators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-simplify-comparison-operators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-simplify-comparison-operators/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-simplify-comparison-operators/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-simplify-comparison-operators/lib/index'>;
}
