// flow-typed signature: 4674cc7802d0af3541913d8474ecd3a4
// flow-typed version: <<STUB>>/bookshelf-signals_v^0.1.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bookshelf-signals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bookshelf-signals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bookshelf-signals/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bookshelf-signals/lib/index.js' {
  declare module.exports: $Exports<'bookshelf-signals/lib/index'>;
}
