// flow-typed signature: 4606403d3b938d0e7cd921728bf24600
// flow-typed version: <<STUB>>/bookshelf-paranoia_v^0.11.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bookshelf-paranoia'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bookshelf-paranoia' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bookshelf-paranoia/test/db/index' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/knexfile' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/migrations/20160414201953_users' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/migrations/20160414202837_articles' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/migrations/20160414203024_tags' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/migrations/20160414203128_articles_tags' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/migrations/20160414203355_comments' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/migrations/20160415000910_sessions' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/migrations/20160808170032_article_or_tag' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/models/article-or-tag' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/models/article-tag' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/models/article' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/models/comment' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/models/session' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/models/tag' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/models/user' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/seeds/0_users' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/seeds/1_articles' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/seeds/2_tags' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/seeds/3_articles_tags' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/seeds/4_comments' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/seeds/5_sessions' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/db/seeds/6_article_or_tag' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/fixtures/custom-db' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/fixtures/timestamper' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/spec/belongs-to-many' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/spec/belongs-to' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/spec/general' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/spec/has-many' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/spec/has-one' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/spec/polymorphism' {
  declare module.exports: any;
}

declare module 'bookshelf-paranoia/test/spec/sentinel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bookshelf-paranoia/index' {
  declare module.exports: $Exports<'bookshelf-paranoia'>;
}
declare module 'bookshelf-paranoia/index.js' {
  declare module.exports: $Exports<'bookshelf-paranoia'>;
}
declare module 'bookshelf-paranoia/test/db/index.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/index'>;
}
declare module 'bookshelf-paranoia/test/db/knexfile.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/knexfile'>;
}
declare module 'bookshelf-paranoia/test/db/migrations/20160414201953_users.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/migrations/20160414201953_users'>;
}
declare module 'bookshelf-paranoia/test/db/migrations/20160414202837_articles.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/migrations/20160414202837_articles'>;
}
declare module 'bookshelf-paranoia/test/db/migrations/20160414203024_tags.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/migrations/20160414203024_tags'>;
}
declare module 'bookshelf-paranoia/test/db/migrations/20160414203128_articles_tags.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/migrations/20160414203128_articles_tags'>;
}
declare module 'bookshelf-paranoia/test/db/migrations/20160414203355_comments.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/migrations/20160414203355_comments'>;
}
declare module 'bookshelf-paranoia/test/db/migrations/20160415000910_sessions.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/migrations/20160415000910_sessions'>;
}
declare module 'bookshelf-paranoia/test/db/migrations/20160808170032_article_or_tag.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/migrations/20160808170032_article_or_tag'>;
}
declare module 'bookshelf-paranoia/test/db/models/article-or-tag.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/models/article-or-tag'>;
}
declare module 'bookshelf-paranoia/test/db/models/article-tag.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/models/article-tag'>;
}
declare module 'bookshelf-paranoia/test/db/models/article.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/models/article'>;
}
declare module 'bookshelf-paranoia/test/db/models/comment.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/models/comment'>;
}
declare module 'bookshelf-paranoia/test/db/models/session.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/models/session'>;
}
declare module 'bookshelf-paranoia/test/db/models/tag.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/models/tag'>;
}
declare module 'bookshelf-paranoia/test/db/models/user.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/models/user'>;
}
declare module 'bookshelf-paranoia/test/db/seeds/0_users.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/seeds/0_users'>;
}
declare module 'bookshelf-paranoia/test/db/seeds/1_articles.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/seeds/1_articles'>;
}
declare module 'bookshelf-paranoia/test/db/seeds/2_tags.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/seeds/2_tags'>;
}
declare module 'bookshelf-paranoia/test/db/seeds/3_articles_tags.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/seeds/3_articles_tags'>;
}
declare module 'bookshelf-paranoia/test/db/seeds/4_comments.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/seeds/4_comments'>;
}
declare module 'bookshelf-paranoia/test/db/seeds/5_sessions.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/seeds/5_sessions'>;
}
declare module 'bookshelf-paranoia/test/db/seeds/6_article_or_tag.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/db/seeds/6_article_or_tag'>;
}
declare module 'bookshelf-paranoia/test/fixtures/custom-db.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/fixtures/custom-db'>;
}
declare module 'bookshelf-paranoia/test/fixtures/timestamper.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/fixtures/timestamper'>;
}
declare module 'bookshelf-paranoia/test/spec/belongs-to-many.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/spec/belongs-to-many'>;
}
declare module 'bookshelf-paranoia/test/spec/belongs-to.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/spec/belongs-to'>;
}
declare module 'bookshelf-paranoia/test/spec/general.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/spec/general'>;
}
declare module 'bookshelf-paranoia/test/spec/has-many.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/spec/has-many'>;
}
declare module 'bookshelf-paranoia/test/spec/has-one.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/spec/has-one'>;
}
declare module 'bookshelf-paranoia/test/spec/polymorphism.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/spec/polymorphism'>;
}
declare module 'bookshelf-paranoia/test/spec/sentinel.js' {
  declare module.exports: $Exports<'bookshelf-paranoia/test/spec/sentinel'>;
}
