// flow-typed signature: cb04a35e5ff1971d5ca8aa35e27211c0
// flow-typed version: <<STUB>>/bookshelf-modelbase_v^2.10.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bookshelf-modelbase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bookshelf-modelbase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bookshelf-modelbase/lib/index' {
  declare module.exports: any;
}

declare module 'bookshelf-modelbase/test/db' {
  declare module.exports: any;
}

declare module 'bookshelf-modelbase/test/index' {
  declare module.exports: any;
}

declare module 'bookshelf-modelbase/test/knexfile' {
  declare module.exports: any;
}

declare module 'bookshelf-modelbase/test/migrations/20141216121111_test-setup' {
  declare module.exports: any;
}

declare module 'bookshelf-modelbase/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bookshelf-modelbase/lib/index.js' {
  declare module.exports: $Exports<'bookshelf-modelbase/lib/index'>;
}
declare module 'bookshelf-modelbase/test/db.js' {
  declare module.exports: $Exports<'bookshelf-modelbase/test/db'>;
}
declare module 'bookshelf-modelbase/test/index.js' {
  declare module.exports: $Exports<'bookshelf-modelbase/test/index'>;
}
declare module 'bookshelf-modelbase/test/knexfile.js' {
  declare module.exports: $Exports<'bookshelf-modelbase/test/knexfile'>;
}
declare module 'bookshelf-modelbase/test/migrations/20141216121111_test-setup.js' {
  declare module.exports: $Exports<'bookshelf-modelbase/test/migrations/20141216121111_test-setup'>;
}
declare module 'bookshelf-modelbase/test/setup.js' {
  declare module.exports: $Exports<'bookshelf-modelbase/test/setup'>;
}
