// flow-typed signature: d133a4e21f3e5db5218073379c5a6035
// flow-typed version: <<STUB>>/caller_v^1.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caller'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caller' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'caller/index' {
  declare module.exports: $Exports<'caller'>;
}
declare module 'caller/index.js' {
  declare module.exports: $Exports<'caller'>;
}
