// flow-typed signature: 55aa0c7b63454e30d00ad40223a06b46
// flow-typed version: <<STUB>>/case_v^1.5.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'case/dist/Case' {
  declare module.exports: any;
}

declare module 'case/dist/Case.min' {
  declare module.exports: any;
}

declare module 'case/dist/Case.plus' {
  declare module.exports: any;
}

declare module 'case/dist/Case.plus.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'case/dist/Case.js' {
  declare module.exports: $Exports<'case/dist/Case'>;
}
declare module 'case/dist/Case.min.js' {
  declare module.exports: $Exports<'case/dist/Case.min'>;
}
declare module 'case/dist/Case.plus.js' {
  declare module.exports: $Exports<'case/dist/Case.plus'>;
}
declare module 'case/dist/Case.plus.min.js' {
  declare module.exports: $Exports<'case/dist/Case.plus.min'>;
}
