// flow-typed signature: 375b9f05f3107f6fbf73d66f5f1084fa
// flow-typed version: <<STUB>>/graphql-bookshelf_v^0.0.8/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-bookshelf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-bookshelf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-bookshelf/config/env' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/config/helpers' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/config/setup' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/connection' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/knexfile' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/migrations/20150812093417_initial_schema' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/models/Classroom' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/models/ClassroomStudent' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/models/Homework' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/models/index' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/models/Student' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/models/Subject' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/schema/ClassroomType' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/schema/HomeworkType' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/schema/index' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/schema/StudentType' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/schema/SubjectType' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/specs/attr-test' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/specs/belongsTo-test' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/specs/hasMany-test' {
  declare module.exports: any;
}

declare module 'graphql-bookshelf/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-bookshelf/config/env.js' {
  declare module.exports: $Exports<'graphql-bookshelf/config/env'>;
}
declare module 'graphql-bookshelf/config/helpers.js' {
  declare module.exports: $Exports<'graphql-bookshelf/config/helpers'>;
}
declare module 'graphql-bookshelf/config/setup.js' {
  declare module.exports: $Exports<'graphql-bookshelf/config/setup'>;
}
declare module 'graphql-bookshelf/connection.js' {
  declare module.exports: $Exports<'graphql-bookshelf/connection'>;
}
declare module 'graphql-bookshelf/index' {
  declare module.exports: $Exports<'graphql-bookshelf'>;
}
declare module 'graphql-bookshelf/index.js' {
  declare module.exports: $Exports<'graphql-bookshelf'>;
}
declare module 'graphql-bookshelf/knexfile.js' {
  declare module.exports: $Exports<'graphql-bookshelf/knexfile'>;
}
declare module 'graphql-bookshelf/migrations/20150812093417_initial_schema.js' {
  declare module.exports: $Exports<'graphql-bookshelf/migrations/20150812093417_initial_schema'>;
}
declare module 'graphql-bookshelf/models/Classroom.js' {
  declare module.exports: $Exports<'graphql-bookshelf/models/Classroom'>;
}
declare module 'graphql-bookshelf/models/ClassroomStudent.js' {
  declare module.exports: $Exports<'graphql-bookshelf/models/ClassroomStudent'>;
}
declare module 'graphql-bookshelf/models/Homework.js' {
  declare module.exports: $Exports<'graphql-bookshelf/models/Homework'>;
}
declare module 'graphql-bookshelf/models/index.js' {
  declare module.exports: $Exports<'graphql-bookshelf/models/index'>;
}
declare module 'graphql-bookshelf/models/Student.js' {
  declare module.exports: $Exports<'graphql-bookshelf/models/Student'>;
}
declare module 'graphql-bookshelf/models/Subject.js' {
  declare module.exports: $Exports<'graphql-bookshelf/models/Subject'>;
}
declare module 'graphql-bookshelf/schema/ClassroomType.js' {
  declare module.exports: $Exports<'graphql-bookshelf/schema/ClassroomType'>;
}
declare module 'graphql-bookshelf/schema/HomeworkType.js' {
  declare module.exports: $Exports<'graphql-bookshelf/schema/HomeworkType'>;
}
declare module 'graphql-bookshelf/schema/index.js' {
  declare module.exports: $Exports<'graphql-bookshelf/schema/index'>;
}
declare module 'graphql-bookshelf/schema/StudentType.js' {
  declare module.exports: $Exports<'graphql-bookshelf/schema/StudentType'>;
}
declare module 'graphql-bookshelf/schema/SubjectType.js' {
  declare module.exports: $Exports<'graphql-bookshelf/schema/SubjectType'>;
}
declare module 'graphql-bookshelf/specs/attr-test.js' {
  declare module.exports: $Exports<'graphql-bookshelf/specs/attr-test'>;
}
declare module 'graphql-bookshelf/specs/belongsTo-test.js' {
  declare module.exports: $Exports<'graphql-bookshelf/specs/belongsTo-test'>;
}
declare module 'graphql-bookshelf/specs/hasMany-test.js' {
  declare module.exports: $Exports<'graphql-bookshelf/specs/hasMany-test'>;
}
declare module 'graphql-bookshelf/src/index.js' {
  declare module.exports: $Exports<'graphql-bookshelf/src/index'>;
}
