// flow-typed signature: 0267d1c8718abdcb6350fac8dbf843a5
// flow-typed version: <<STUB>>/hide-stack-frames-from_vyknx4/hide-stack-frames-from/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hide-stack-frames-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hide-stack-frames-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hide-stack-frames-from/index' {
  declare module.exports: $Exports<'hide-stack-frames-from'>;
}
declare module 'hide-stack-frames-from/index.js' {
  declare module.exports: $Exports<'hide-stack-frames-from'>;
}
