// flow-typed signature: 6e6283e66cd29910a2498d85a3b5cb4f
// flow-typed version: <<STUB>>/jest-diff_v^20.0.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-diff/build-es5/constants' {
  declare module.exports: any;
}

declare module 'jest-diff/build-es5/diffStrings' {
  declare module.exports: any;
}

declare module 'jest-diff/build-es5/index' {
  declare module.exports: any;
}

declare module 'jest-diff/build/constants' {
  declare module.exports: any;
}

declare module 'jest-diff/build/diffStrings' {
  declare module.exports: any;
}

declare module 'jest-diff/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-diff/build-es5/constants.js' {
  declare module.exports: $Exports<'jest-diff/build-es5/constants'>;
}
declare module 'jest-diff/build-es5/diffStrings.js' {
  declare module.exports: $Exports<'jest-diff/build-es5/diffStrings'>;
}
declare module 'jest-diff/build-es5/index.js' {
  declare module.exports: $Exports<'jest-diff/build-es5/index'>;
}
declare module 'jest-diff/build/constants.js' {
  declare module.exports: $Exports<'jest-diff/build/constants'>;
}
declare module 'jest-diff/build/diffStrings.js' {
  declare module.exports: $Exports<'jest-diff/build/diffStrings'>;
}
declare module 'jest-diff/build/index.js' {
  declare module.exports: $Exports<'jest-diff/build/index'>;
}
