// flow-typed signature: fa8723805acc9cc7b41367bcf297c049
// flow-typed version: <<STUB>>/knex-cleaner_v^1.1.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'knex-cleaner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'knex-cleaner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'knex-cleaner/lib/knex_cleaner' {
  declare module.exports: any;
}

declare module 'knex-cleaner/lib/knex_tables' {
  declare module.exports: any;
}

declare module 'knex-cleaner/test/knex_cleaner' {
  declare module.exports: any;
}

declare module 'knex-cleaner/test/knex_tables' {
  declare module.exports: any;
}

declare module 'knex-cleaner/test/knex_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'knex-cleaner/lib/knex_cleaner.js' {
  declare module.exports: $Exports<'knex-cleaner/lib/knex_cleaner'>;
}
declare module 'knex-cleaner/lib/knex_tables.js' {
  declare module.exports: $Exports<'knex-cleaner/lib/knex_tables'>;
}
declare module 'knex-cleaner/test/knex_cleaner.js' {
  declare module.exports: $Exports<'knex-cleaner/test/knex_cleaner'>;
}
declare module 'knex-cleaner/test/knex_tables.js' {
  declare module.exports: $Exports<'knex-cleaner/test/knex_tables'>;
}
declare module 'knex-cleaner/test/knex_test.js' {
  declare module.exports: $Exports<'knex-cleaner/test/knex_test'>;
}
