// flow-typed signature: c911015b36fd03c95b982f5688ddbfbc
// flow-typed version: <<STUB>>/knex-migrate_v^1.3.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'knex-migrate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'knex-migrate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'knex-migrate/lib/cli' {
  declare module.exports: any;
}

declare module 'knex-migrate/lib/storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'knex-migrate/lib/cli.js' {
  declare module.exports: $Exports<'knex-migrate/lib/cli'>;
}
declare module 'knex-migrate/lib/storage.js' {
  declare module.exports: $Exports<'knex-migrate/lib/storage'>;
}
