// flow-typed signature: b019458f5febb3a01b765c0477a4e429
// flow-typed version: <<STUB>>/nscript_v^0.1.10/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nscript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nscript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nscript/lib/command' {
  declare module.exports: any;
}

declare module 'nscript/lib/index' {
  declare module.exports: any;
}

declare module 'nscript/lib/repl' {
  declare module.exports: any;
}

declare module 'nscript/lib/shell' {
  declare module.exports: any;
}

declare module 'nscript/lib/spawn' {
  declare module.exports: any;
}

declare module 'nscript/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nscript/lib/command.js' {
  declare module.exports: $Exports<'nscript/lib/command'>;
}
declare module 'nscript/lib/index.js' {
  declare module.exports: $Exports<'nscript/lib/index'>;
}
declare module 'nscript/lib/repl.js' {
  declare module.exports: $Exports<'nscript/lib/repl'>;
}
declare module 'nscript/lib/shell.js' {
  declare module.exports: $Exports<'nscript/lib/shell'>;
}
declare module 'nscript/lib/spawn.js' {
  declare module.exports: $Exports<'nscript/lib/spawn'>;
}
declare module 'nscript/lib/utils.js' {
  declare module.exports: $Exports<'nscript/lib/utils'>;
}
