// flow-typed signature: 99977a86b9dc1f654e6008fe1913564a
// flow-typed version: <<STUB>>/paginator_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'paginator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'paginator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'paginator/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'paginator/example.js' {
  declare module.exports: $Exports<'paginator/example'>;
}
declare module 'paginator/index' {
  declare module.exports: $Exports<'paginator'>;
}
declare module 'paginator/index.js' {
  declare module.exports: $Exports<'paginator'>;
}
