// flow-typed signature: 262fe8690ca348cea8b9340fce9a4fd9
// flow-typed version: <<STUB>>/relay-cursor-paging_v^0.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-cursor-paging'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-cursor-paging' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-cursor-paging/lib/checkPagingSanity' {
  declare module.exports: any;
}

declare module 'relay-cursor-paging/lib/getPagingParameters' {
  declare module.exports: any;
}

declare module 'relay-cursor-paging/lib/index' {
  declare module.exports: any;
}

declare module 'relay-cursor-paging/lib/interfaces' {
  declare module.exports: any;
}

declare module 'relay-cursor-paging/lib/pageable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-cursor-paging/lib/checkPagingSanity.js' {
  declare module.exports: $Exports<'relay-cursor-paging/lib/checkPagingSanity'>;
}
declare module 'relay-cursor-paging/lib/getPagingParameters.js' {
  declare module.exports: $Exports<'relay-cursor-paging/lib/getPagingParameters'>;
}
declare module 'relay-cursor-paging/lib/index.js' {
  declare module.exports: $Exports<'relay-cursor-paging/lib/index'>;
}
declare module 'relay-cursor-paging/lib/interfaces.js' {
  declare module.exports: $Exports<'relay-cursor-paging/lib/interfaces'>;
}
declare module 'relay-cursor-paging/lib/pageable.js' {
  declare module.exports: $Exports<'relay-cursor-paging/lib/pageable'>;
}
