// flow-typed signature: 78e47bf43571058be5f158aa517b5d64
// flow-typed version: <<STUB>>/tracerdebug_v^0.8.9/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tracerdebug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tracerdebug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tracerdebug/dummy' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/colorConsole' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/colorConsole2' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/config' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/console' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/dailyfile' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/depth' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/express/app' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/express/config' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/express/routes/index' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/file' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/filter' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/format' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/format2' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/format3' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/format4' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/formatJson' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/hourlog' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/level' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/methods' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/mongodb' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/multipleTransport' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/setLevel' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/setLevelAnother' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/stream' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/stress' {
  declare module.exports: any;
}

declare module 'tracerdebug/example/test' {
  declare module.exports: any;
}

declare module 'tracerdebug/lib/color_console' {
  declare module.exports: any;
}

declare module 'tracerdebug/lib/console' {
  declare module.exports: any;
}

declare module 'tracerdebug/lib/dailyfile' {
  declare module.exports: any;
}

declare module 'tracerdebug/lib/index' {
  declare module.exports: any;
}

declare module 'tracerdebug/lib/settings' {
  declare module.exports: any;
}

declare module 'tracerdebug/lib/utils' {
  declare module.exports: any;
}

declare module 'tracerdebug/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tracerdebug/dummy.js' {
  declare module.exports: $Exports<'tracerdebug/dummy'>;
}
declare module 'tracerdebug/example/colorConsole.js' {
  declare module.exports: $Exports<'tracerdebug/example/colorConsole'>;
}
declare module 'tracerdebug/example/colorConsole2.js' {
  declare module.exports: $Exports<'tracerdebug/example/colorConsole2'>;
}
declare module 'tracerdebug/example/config.js' {
  declare module.exports: $Exports<'tracerdebug/example/config'>;
}
declare module 'tracerdebug/example/console.js' {
  declare module.exports: $Exports<'tracerdebug/example/console'>;
}
declare module 'tracerdebug/example/dailyfile.js' {
  declare module.exports: $Exports<'tracerdebug/example/dailyfile'>;
}
declare module 'tracerdebug/example/depth.js' {
  declare module.exports: $Exports<'tracerdebug/example/depth'>;
}
declare module 'tracerdebug/example/express/app.js' {
  declare module.exports: $Exports<'tracerdebug/example/express/app'>;
}
declare module 'tracerdebug/example/express/config.js' {
  declare module.exports: $Exports<'tracerdebug/example/express/config'>;
}
declare module 'tracerdebug/example/express/routes/index.js' {
  declare module.exports: $Exports<'tracerdebug/example/express/routes/index'>;
}
declare module 'tracerdebug/example/file.js' {
  declare module.exports: $Exports<'tracerdebug/example/file'>;
}
declare module 'tracerdebug/example/filter.js' {
  declare module.exports: $Exports<'tracerdebug/example/filter'>;
}
declare module 'tracerdebug/example/format.js' {
  declare module.exports: $Exports<'tracerdebug/example/format'>;
}
declare module 'tracerdebug/example/format2.js' {
  declare module.exports: $Exports<'tracerdebug/example/format2'>;
}
declare module 'tracerdebug/example/format3.js' {
  declare module.exports: $Exports<'tracerdebug/example/format3'>;
}
declare module 'tracerdebug/example/format4.js' {
  declare module.exports: $Exports<'tracerdebug/example/format4'>;
}
declare module 'tracerdebug/example/formatJson.js' {
  declare module.exports: $Exports<'tracerdebug/example/formatJson'>;
}
declare module 'tracerdebug/example/hourlog.js' {
  declare module.exports: $Exports<'tracerdebug/example/hourlog'>;
}
declare module 'tracerdebug/example/level.js' {
  declare module.exports: $Exports<'tracerdebug/example/level'>;
}
declare module 'tracerdebug/example/methods.js' {
  declare module.exports: $Exports<'tracerdebug/example/methods'>;
}
declare module 'tracerdebug/example/mongodb.js' {
  declare module.exports: $Exports<'tracerdebug/example/mongodb'>;
}
declare module 'tracerdebug/example/multipleTransport.js' {
  declare module.exports: $Exports<'tracerdebug/example/multipleTransport'>;
}
declare module 'tracerdebug/example/setLevel.js' {
  declare module.exports: $Exports<'tracerdebug/example/setLevel'>;
}
declare module 'tracerdebug/example/setLevelAnother.js' {
  declare module.exports: $Exports<'tracerdebug/example/setLevelAnother'>;
}
declare module 'tracerdebug/example/stream.js' {
  declare module.exports: $Exports<'tracerdebug/example/stream'>;
}
declare module 'tracerdebug/example/stress.js' {
  declare module.exports: $Exports<'tracerdebug/example/stress'>;
}
declare module 'tracerdebug/example/test.js' {
  declare module.exports: $Exports<'tracerdebug/example/test'>;
}
declare module 'tracerdebug/index' {
  declare module.exports: $Exports<'tracerdebug'>;
}
declare module 'tracerdebug/index.js' {
  declare module.exports: $Exports<'tracerdebug'>;
}
declare module 'tracerdebug/lib/color_console.js' {
  declare module.exports: $Exports<'tracerdebug/lib/color_console'>;
}
declare module 'tracerdebug/lib/console.js' {
  declare module.exports: $Exports<'tracerdebug/lib/console'>;
}
declare module 'tracerdebug/lib/dailyfile.js' {
  declare module.exports: $Exports<'tracerdebug/lib/dailyfile'>;
}
declare module 'tracerdebug/lib/index.js' {
  declare module.exports: $Exports<'tracerdebug/lib/index'>;
}
declare module 'tracerdebug/lib/settings.js' {
  declare module.exports: $Exports<'tracerdebug/lib/settings'>;
}
declare module 'tracerdebug/lib/utils.js' {
  declare module.exports: $Exports<'tracerdebug/lib/utils'>;
}
declare module 'tracerdebug/test/test.js' {
  declare module.exports: $Exports<'tracerdebug/test/test'>;
}
